import '../scss/style.scss'
import './variables'
import './script'
import './ButtonOpenHide'
import './technicaButton'
import './buttonBurger'
import './buttonCross'
import './buttonCall';
import './buttonFeedback';